ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
UPDATE usuarios SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE usuarios ALTER COLUMN ativo SET NOT NULL;

ALTER TABLE caixas_dagua ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
UPDATE caixas_dagua SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE caixas_dagua ALTER COLUMN ativo SET NOT NULL;