ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
UPDATE usuarios SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE usuarios MODIFY COLUMN ativo BOOLEAN NOT NULL;

ALTER TABLE caixas_dagua ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
UPDATE caixas_dagua SET ativo = TRUE WHERE ativo IS NULL;
ALTER TABLE caixas_dagua MODIFY COLUMN ativo BOOLEAN NOT NULL;