spring:
  application:
      name: api
  datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_API_USER}
    password: ${MAILTRAP_API_TOKEN}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

api:
  security:
      token:
          secret: ${JWT_SECRET}
          expiration-hours: 2